version: 2
jobs:
  build:

    working_directory: ~/quarkus_demo_circleci

    docker:
      - image: circleci/openjdk:11-jdk-stretch
        environment:
          POSTGRE_HOST: localhost
      - image: quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: ffzs
          POSTGRES_PASSWORD: 123zxc
          POSTGRES_DB: mydb

    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: chmod +x mvnw
      - run: ./mvnw package -Dquarkus.package.type=uber-jar
      - run: docker login -u ffzs -p $DOCKERHUB_PASSWORD
      - run: docker build -f src/main/docker/Dockerfile.jvm -t ffzs/quarkus_demo . && docker push ffzs/quarkus_demo

      - store_artifacts:
          path: target/create_demo-1.0.0-SNAPSHOT-runner.jar

