version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
        environment:
          POSTGRE_HOST: localhost
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: ffzs
          POSTGRES_PASSWORD: 123zxc
          POSTGRES_DB: mydb

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: chmod +x mvnw
      - run: ./mvnw package -Dquarkus.package.type=uber-jar
      - run: docker login -u ffzs -p $DOCKERHUB_PASSWORD
      - run: docker build -f src/main/docker/Dockerfile.fast-jar -t ffzs/quarkus_demo . && docker push ffzs/quarkus_demo


