version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
        environment:
          POSTGRE_HOST: localhost
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: ffzs
          POSTGRES_PASSWORD: 123zxc
          POSTGRES_DB: mydb

    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: build docker image
          shell: /bin/bash
          command: |
            chmod +x mvnw
            ./mvnw package -Dquarkus.package.type=uber-jar
            docker login -u ffzs -p $DOCKERHUB_PASSWORD
            cd target/quarkus-app
            echo "$PWD"
            ls
            cp src/main/docker/Dockerfile.fast-jar Dockerfile
            docker build -t ffzs/quarkus_demo .
            docker push ffzs/quarkus_demo


