version: 2
jobs:
  build:

    working_directory: ~/quarkus_demo_circleci

    docker:
      - image: circleci/openjdk:11-jdk-stretch
        environment:
          POSTGRE_HOST: localhost
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: ffzs
          POSTGRES_PASSWORD: 123zxc
          POSTGRES_DB: mydb

    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - setup_remote_docker:
          version: 19.03.13
      - run: chmod +x mvnw
      - run: ./mvnw package -Pnative -Dquarkus.native.container-build=true
      - run: docker login -u ffzs -p $DOCKERHUB_PASSWORD
      - run: docker build -f src/main/docker/Dockerfile.native -t ffzs/quarkus_demo . && docker push ffzs/quarkus_demo


